# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\x05mlops\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x0bHealthReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\xb2\x01\n\x0cTrainRequest\x12\x11\n\tmodel_key\x18\x01 \x01(\t\x12\x12\n\ndataset_id\x18\x02 \x01(\t\x12\x15\n\rtarget_column\x18\x03 \x01(\t\x12\x18\n\x10hyperparams_json\x18\x04 \x01(\t\x12\x11\n\ttest_size\x18\x05 \x01(\x01\x12\x0f\n\x07shuffle\x18\x06 \x01(\x08\x12\x14\n\x0crandom_state\x18\x07 \x01(\x05\x12\x10\n\x08model_id\x18\x08 \x01(\t\"\x92\x01\n\nTrainReply\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x11\n\tmodel_key\x18\x02 \x01(\t\x12/\n\x07metrics\x18\x03 \x03(\x0b\x32\x1e.mlops.TrainReply.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\":\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x16\n\x0einstances_json\x18\x02 \x01(\t\"\x1c\n\nDoubleList\x12\x0e\n\x06values\x18\x01 \x03(\x01\"M\n\x0cPredictReply\x12\x13\n\x0bpredictions\x18\x01 \x03(\t\x12(\n\rprobabilities\x18\x02 \x03(\x0b\x32\x11.mlops.DoubleList\"o\n\tModelInfo\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x11\n\tmodel_key\x18\x02 \x01(\t\x12\x12\n\ndataset_id\x18\x03 \x01(\t\x12\x15\n\rtarget_column\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"2\n\x0fListModelsReply\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.mlops.ModelInfo\"&\n\x12\x44\x65leteModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"#\n\x10\x44\x65leteModelReply\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\xaa\x02\n\tMLService\x12\x34\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x12.mlops.HealthReply\x12/\n\x05Train\x12\x13.mlops.TrainRequest\x1a\x11.mlops.TrainReply\x12\x35\n\x07Predict\x12\x15.mlops.PredictRequest\x1a\x13.mlops.PredictReply\x12<\n\nListModels\x12\x16.google.protobuf.Empty\x1a\x16.mlops.ListModelsReply\x12\x41\n\x0b\x44\x65leteModel\x12\x19.mlops.DeleteModelRequest\x1a\x17.mlops.DeleteModelReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREPLY_METRICSENTRY']._loaded_options = None
  _globals['_TRAINREPLY_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHREPLY']._serialized_start=56
  _globals['_HEALTHREPLY']._serialized_end=85
  _globals['_TRAINREQUEST']._serialized_start=88
  _globals['_TRAINREQUEST']._serialized_end=266
  _globals['_TRAINREPLY']._serialized_start=269
  _globals['_TRAINREPLY']._serialized_end=415
  _globals['_TRAINREPLY_METRICSENTRY']._serialized_start=369
  _globals['_TRAINREPLY_METRICSENTRY']._serialized_end=415
  _globals['_PREDICTREQUEST']._serialized_start=417
  _globals['_PREDICTREQUEST']._serialized_end=475
  _globals['_DOUBLELIST']._serialized_start=477
  _globals['_DOUBLELIST']._serialized_end=505
  _globals['_PREDICTREPLY']._serialized_start=507
  _globals['_PREDICTREPLY']._serialized_end=584
  _globals['_MODELINFO']._serialized_start=586
  _globals['_MODELINFO']._serialized_end=697
  _globals['_LISTMODELSREPLY']._serialized_start=699
  _globals['_LISTMODELSREPLY']._serialized_end=749
  _globals['_DELETEMODELREQUEST']._serialized_start=751
  _globals['_DELETEMODELREQUEST']._serialized_end=789
  _globals['_DELETEMODELREPLY']._serialized_start=791
  _globals['_DELETEMODELREPLY']._serialized_end=826
  _globals['_MLSERVICE']._serialized_start=829
  _globals['_MLSERVICE']._serialized_end=1127
# @@protoc_insertion_point(module_scope)
